version: '3.1'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movie_list_db
    ports:
      - "3306:3306"
      - "33060:33060"
    networks:
      - movie-list-network

  my-movie-list:
    build: 
      dockerfile: ./Dockerfile
      context: .
    image: pedro/my-movie-list
    container_name: smy-movie-list-container
    ports:
      - "8081:8081"
    networks: 
      - movie-list-network
    environment: 
      WAIT_HOSTS: mysql:3306 
      SPRING_PROFILES_ACTIVE: prod 
      MONGO_DB_PASSWORD: mongodb12358
      MOVIE_API_KEY: a14d836ba9872e3582094edabf7ff1b0
    depends_on: 
      - "mysql"

networks:
  movie-list-network:
    driver: bridge