version: '3.1'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movie_list_db
    ports:
      - "3306:3306"
      - "33060:33060"
    networks:
      - movie-list-network

networks:
  movie-list-network:
    driver: bridge